{% set name = "photutils" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/photutils/photutils-{{ version }}.tar.gz
  sha256: 947527f77794469f960d51e6fd7add2fd531b16f2369d4541b1441eb81b3d9f7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.0,<4                      # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=77.0
    - setuptools_scm >=8.0
    - cython >=3.1.0,<4
    - extension-helpers >=1.3,<2
    - astropy-base >=5.3
    - numpy
  run:
    - python
    - numpy >=1.25
    - astropy-base >=5.3
    - scipy >=1.11.1
    - matplotlib-base >=3.8
    - regions >=0.9
    - scikit-image >=0.21
    - gwcs >=0.20
    - bottleneck >=1.3.6
    - tqdm >=4.65
    - rasterio >=1.3.7
    - shapely >=2.0.0

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.profiles
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - larrybradley
    - bsipocz
    - mwcraig
