{% set name = "photutils" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/photutils/photutils-{{ version }}.tar.gz
  sha256: 309532a60a9395358f468a5d5a53db19ccd0c02363882f94e903ffa87f2ae772

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.0,<3.1.0                  # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=6.2
    - cython >=3.0.0,<3.1.0
    - extension-helpers
    - astropy >=5.3
    - numpy
  run:
    - python
    - numpy >=1.24
    - astropy >=5.3
    - scipy >=1.10
    - matplotlib-base >=3.7
    - regions >=0.9
    - scikit-image >=0.20
    - gwcs >=0.19
    - bottleneck
    - tqdm
    - rasterio
    - shapely

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.profiles
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - larrybradley
    - bsipocz
    - mwcraig
