{% set name = "photutils" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8426eea49c06fc348884c92d96e7b2f2d9ea2ecd259b5acec25bb3eec26ecdd4


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.0,<3.1.0                  # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=6.2
    - cython >=3.0.0,<3.1.0
    - extension-helpers
    - astropy >=5.1
    - numpy
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - astropy >=5.1
    - gwcs >=0.18
    - matplotlib-base >=3.5
    - scikit-image >=0.20
    - scikit-learn >=1.1
    - scipy >=1.8
    - bottleneck
    - tqdm
    - rasterio
    - shapely

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.profiles
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - larrybradley
    - bsipocz
    - mwcraig
