{% set name = "photutils" %}
{% set version = "0.7.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4cd94de12e3496d44be85b62b22cfc6bad382a74b2e737c21602e7d6aa2223bf" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  # Note: pip-based install fails due to wanting to download astropy-helpers
  script: python setup.py install --offline --single-version-externally-managed --record=files.txt
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy >=1.13
  run:
    - python
    - numpy >=1.13
    - astropy >=2.0
    - scipy
    - matplotlib>=2.2
    - scikit-image >=0.14.2
    - scikit-learn
    - gwcs >=0.11

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - larrybradley
