{% set name = "photutils" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6da7f1bfef5f445161bc6f3fa4a6ae9599c727183c4f93c6e6e24aac0ced9370


build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - cython >=0.29.30
    - extension-helpers
    - numpy 1.18.*  # [py<39 and build_platform == target_platform and python_impl == 'cpython']
    - numpy  # [py>=39 or build_platform != target_platform or python_impl == 'pypy']
    - astropy >=5.0
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - numpy >=1.20
    - astropy >=5.0
    - pytest-astropy >=0.4
    - gwcs >=0.16
    - matplotlib-base >=3.3
    - scikit-image >=0.18.0
    - scikit-learn >=1.0
    - scipy >=1.6.0
    - bottleneck
    - tqdm

test:
  requires:
    - pytest-astropy
  imports:
    - photutils
    - photutils.aperture
    - photutils.background
    - photutils.centroids
    - photutils.datasets
    - photutils.detection
    - photutils.extern
    - photutils.geometry
    - photutils.isophote
    - photutils.morphology
    - photutils.psf
    - photutils.psf.matching
    - photutils.segmentation
    - photutils.utils

about:
  home: https://photutils.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: An Astropy package for photometry
  description: |
    Photutils is an Astropy package for detection and photometry of
    astronomical sources.
  doc_url: https://photutils.readthedocs.io/
  dev_url: https://github.com/astropy/photutils

extra:
  recipe-maintainers:
    - larrybradley
    - bsipocz
    - mwcraig
